# Generated by Django 4.2.25 on 2025-10-27 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('communicable', 'Communicable'), ('non-communicable', 'Non-Communicable')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EpidemiologicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField()),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.country')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.disease')),
            ],
        ),
    ]
